// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Xf__mF_dGq6dj8E0ANh3oQHti2E53RE',
    appId: '1:834150608261:web:00bfbec615e588abe5e8ec',
    messagingSenderId: '834150608261',
    projectId: 'todo-320b4',
    authDomain: 'todo-320b4.firebaseapp.com',
    storageBucket: 'todo-320b4.appspot.com',
    measurementId: 'G-32P1YLZT3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7cY5qPtvGGsNRph5oVeYOHAdsaOYqalQ',
    appId: '1:834150608261:android:67ff88ba37abb389e5e8ec',
    messagingSenderId: '834150608261',
    projectId: 'todo-320b4',
    storageBucket: 'todo-320b4.appspot.com',
  );

}